# @package _global_

# B3: Warped Double Well (2D)
dim: 2

energy:
  _target_: adjoint_samplers.energies.synthetic_energies.WarpedDoubleWellEnergy
  dim: ${dim}
  gamma: ${gamma}

evaluator:
  _target_: adjoint_samplers.components.synthetic_2d_evaluator.Synthetic2DEvaluator
  n_ref_samples: 50000
  grid_size: 500
